version: '3'

services:

  mariadb:
    build: requirements/mariadb
    image: mariadb
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - chabaka
    restart: on-failure

  nginx:
    depends_on:
      - wordpress
    build: requirements/nginx
    image: nginx
    ports:
      - '443:443'
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - chabaka
    restart: on-failure

  wordpress:
    depends_on:
      - mariadb
    build: requirements/wordpress
    image: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - chabaka
    restart: on-failure

volumes:
  wordpress:
    driver: local
    driver_opts:
      device: '/home/ochouikh/data/wordpress'
      o: 'bind'
      type: 'none'

  mariadb:
    driver: local
    driver_opts:
      device: '/home/ochouikh/data/mariadb'
      o: 'bind'
      type: 'none'

networks:
  chabaka:
